name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - '*'

permissions:
  contents: read

concurrency:
  # Make sure we only run one pipeline at a time for this branch.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fmt_and_clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1.9
        with:
          components: rustfmt, clippy

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        timeout-minutes: 10

      - run: cargo fmt --all -- --check
      - run: cargo build --verbose
      - run: cargo clippy --all-targets